"""
Generate a small test system for the cpptraj IDE:
  - test_topology.pdb   : 10-residue alanine helix (single frame, used as topology)
  - test_trajectory.pdb : 200-frame multi-MODEL PDB with realistic MD-like motion

Both files work directly with cpptraj (parm test_topology.pdb / trajin test_trajectory.pdb).
"""

import numpy as np
from pathlib import Path

OUT = Path(__file__).parent / "test_data"
OUT.mkdir(exist_ok=True)

RNG = np.random.default_rng(42)

# ─────────────────────────────────────────────────────────────────────────────
# Build a 10-residue polyalanine alpha-helix
# ─────────────────────────────────────────────────────────────────────────────
# Ideal alpha-helix rise/residue = 1.5 Å, rotation = 100° per residue
# Helix radius ~2.3 Å for Cα
N_RES   = 10
N_FRAMES= 200

RESIDUES = ["ALA"] * N_RES

# Backbone atoms per residue: N, CA, C, O  (+CB for alanine)
BACKBONE = ["N", "CA", "C", "O", "CB"]

def helix_coords(n_res, rise=1.5, radius=2.3, omega=np.radians(100)):
    """Generate ideal alpha-helix Cα positions."""
    coords = []
    for i in range(n_res):
        theta = i * omega
        x = radius * np.cos(theta)
        y = radius * np.sin(theta)
        z = i * rise
        coords.append([x, y, z])
    return np.array(coords)

def build_residue(ca, res_idx):
    """Place N, CA, C, O, CB around a Cα position with ideal bond geometry."""
    ca = np.array(ca)
    atoms = {}
    # Cα
    atoms["CA"] = ca
    # N: ~1.46 Å from CA, offset
    atoms["N"]  = ca + np.array([-1.20, -0.55,  0.30])
    # C: ~1.52 Å from CA
    atoms["C"]  = ca + np.array([ 1.40, -0.25, -0.10])
    # O: from C
    atoms["O"]  = atoms["C"] + np.array([ 0.50,  1.10, -0.30])
    # CB: tetrahedral from CA
    atoms["CB"] = ca + np.array([-0.10,  1.40, -0.60])
    return atoms

# Build reference coordinates
ca_positions = helix_coords(N_RES)
ref_atoms = []   # list of (resnum, resname, atomname, xyz)

atom_serial = 1
for i, ca in enumerate(ca_positions):
    resnum  = i + 1
    resname = "ALA"
    res_dict = build_residue(ca, i)
    for atom_name in BACKBONE:
        ref_atoms.append((resnum, resname, atom_name, res_dict[atom_name].copy()))

N_ATOMS = len(ref_atoms)
ref_xyz = np.array([a[3] for a in ref_atoms])  # (N_ATOMS, 3)

# ─────────────────────────────────────────────────────────────────────────────
# PDB WRITER
# ─────────────────────────────────────────────────────────────────────────────
def write_pdb_frame(fh, xyz, atoms, model=None):
    if model is not None:
        fh.write(f"MODEL     {model:4d}\n")
    for idx, (resnum, resname, atomname, _) in enumerate(atoms):
        x, y, z = xyz[idx]
        # PDB ATOM record
        fh.write(
            f"ATOM  {idx+1:5d}  {atomname:<3s} {resname:3s} A{resnum:4d}    "
            f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           {atomname[0]:>2s}\n"
        )
    if model is not None:
        fh.write("ENDMDL\n")
    else:
        fh.write("END\n")

# ─────────────────────────────────────────────────────────────────────────────
# Write topology (single frame)
# ─────────────────────────────────────────────────────────────────────────────
topo_path = OUT / "test_topology.pdb"
with open(topo_path, "w") as f:
    f.write("REMARK  Test topology — 10-residue polyalanine alpha-helix\n")
    f.write(f"REMARK  Generated by generate_test_traj.py\n")
    write_pdb_frame(f, ref_xyz, ref_atoms)

print(f"Written: {topo_path}  ({N_ATOMS} atoms, {N_RES} residues)")

# ─────────────────────────────────────────────────────────────────────────────
# Generate MD-like motion for the trajectory
# ─────────────────────────────────────────────────────────────────────────────
# Simulate: slow helix breathing + random thermal noise + small overall tumbling
traj_path = OUT / "test_trajectory.pdb"

with open(traj_path, "w") as f:
    f.write("REMARK  Test trajectory — 200 frames, polyalanine helix MD-like motion\n")
    f.write("REMARK  Use with test_topology.pdb\n")

    for frame in range(N_FRAMES):
        t = frame / N_FRAMES  # 0..1

        # 1. Slow breathing (helix expansion/contraction, ~0.5 Å amplitude)
        breath_scale = 1.0 + 0.08 * np.sin(2 * np.pi * t * 3)

        # 2. Slow end-to-end unfolding tendency then refolding
        unfold = 0.3 * np.sin(2 * np.pi * t) * np.linspace(0, 1, N_ATOMS)

        # 3. Small overall rotation (tumbling)
        angle = 0.4 * np.sin(2 * np.pi * t * 1.5)
        rot = np.array([
            [np.cos(angle), -np.sin(angle), 0],
            [np.sin(angle),  np.cos(angle), 0],
            [0,              0,             1],
        ])

        # 4. Thermal noise (Gaussian, ~0.3 Å std)
        noise = RNG.normal(0, 0.25, ref_xyz.shape)

        # Build perturbed frame
        xyz = ref_xyz.copy()
        # center, scale, rotate, add noise and unfold
        com = xyz.mean(axis=0)
        xyz -= com
        xyz *= breath_scale
        xyz = (rot @ xyz.T).T
        xyz += com
        xyz[:, 2] += unfold  # z-axis unfolding
        xyz += noise

        write_pdb_frame(f, xyz, ref_atoms, model=frame + 1)

print(f"Written: {traj_path}  ({N_FRAMES} frames)")

# ─────────────────────────────────────────────────────────────────────────────
# Also write a quick README for the test_data folder
# ─────────────────────────────────────────────────────────────────────────────
readme = OUT / "README.txt"
readme.write_text(f"""\
Test files for cpptraj IDE
==========================
System : 10-residue polyalanine alpha-helix
Atoms  : {N_ATOMS} atoms ({N_RES} residues x 5 backbone atoms: N, CA, C, O, CB)
Frames : {N_FRAMES}

Files
-----
test_topology.pdb   — single-frame PDB, use as topology (parm)
test_trajectory.pdb — multi-MODEL PDB, use as trajectory (trajin)

Example cpptraj script
----------------------
parm  test_topology.pdb
trajin test_trajectory.pdb

autoimage

rmsd backbone @CA,C,N,O first out rmsd.dat
atomicfluct rmsf @CA byres out rmsf.dat
radgyr rg @CA mass out rg.dat
hbond hbonds out hbond.dat avgout hbond_avg.dat
secstruct ss out secstruct.dat sumout secstruct_sum.dat

go
""")
print(f"Written: {readme}")
print("\nAll test files ready in:  test_data/")
